### ISSUE TITLE
Make this LoRa shield also compatible with T-SIM & T-CALL 

### ISSUE THREAD

**Issue by nikil511** [Xinyuan-LilyGO/LilyGO-T-HiGrow-LoRaWLAN#1]
By adding LoRa to ESP32-GSM modem backed boards (T-SIM & T-CALL) you create a very powerful gateway for other LoRa sensors. 

For example, you could have a few T-HiGrow+LoRa sensors, sending to T-SIM+LoRa which in turn uploads periodically to the cloud via NBIoT. 

Additional, nice to have features:
- external RTC like T-Fox (ESP32 internal RTC is very inaccurate and you need a good RTC for synchronized sleep in WSN) 
- MOSFETs or regulated power output for turning on/off external peripheral sensors. 
- Solar charger (Maybe this could be combined with the MOSFET output above with a feature full power management chip ?)

**Comment by lewisxhe** [comment]
A T-SIM adaptation has been made, but T-Call does not. I will close the question, please reopen if there is still a problem
